In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('../session2/data/sales_data_sample.csv',encoding='ISO-8859-1')

In [3]:
df1.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [30]:
df1[['QUANTITYORDERED','SALES']]

      QUANTITYORDERED    SALES
0                  30  2871.00
1                  34  2765.90
2                  41  3884.34
3                  45  3746.70
4                  49  5205.27
...               ...      ...
2818               20  2244.40
2819               29  3978.51
2820               43  5417.57
2821               34  2116.16
2822               47  3079.44

[2823 rows x 2 columns]

In [4]:
df1.select_dtypes(['float'])

      PRICEEACH    SALES
0         95.70  2871.00
1         81.35  2765.90
2         94.74  3884.34
3         83.26  3746.70
4        100.00  5205.27
...         ...      ...
2818     100.00  2244.40
2819     100.00  3978.51
2820     100.00  5417.57
2821      62.24  2116.16
2822      65.52  3079.44

[2823 rows x 2 columns]

In [7]:
df1[df1.columns[2:5]]

      PRICEEACH  ORDERLINENUMBER    SALES
0         95.70                2  2871.00
1         81.35                5  2765.90
2         94.74                2  3884.34
3         83.26                6  3746.70
4        100.00               14  5205.27
...         ...              ...      ...
2818     100.00               15  2244.40
2819     100.00                1  3978.51
2820     100.00                4  5417.57
2821      62.24                1  2116.16
2822      65.52                9  3079.44

[2823 rows x 3 columns]

In [10]:
df1.loc[10:20:,['CUSTOMERNAME','STATE']]

                  CUSTOMERNAME     STATE
10  Australian Collectors, Co.  Victoria
11             Vitachrome Inc.        NY
12     Tekni Collectables Inc.        NJ
13             Gift Depot Inc.        CT
14           La Rochelle Gifts       NaN
15        Marta's Replicas Co.        MA
16        Toys of Finland, Co.       NaN
17          Baane Mini Imports       NaN
18       Diecast Classics Inc.        PA
19           Land of Toys Inc.        NY
20       Salzburg Collectables       NaN

In [20]:
#df1.iloc[10:20,2:5]
df1.iloc[:,[2,4,7,8,10]]

      PRICEEACH    SALES  QTR_ID  MONTH_ID  PRODUCTLINE
0         95.70  2871.00       1         2  Motorcycles
1         81.35  2765.90       2         5  Motorcycles
2         94.74  3884.34       3         7  Motorcycles
3         83.26  3746.70       3         8  Motorcycles
4        100.00  5205.27       4        10  Motorcycles
...         ...      ...     ...       ...          ...
2818     100.00  2244.40       4        12        Ships
2819     100.00  3978.51       1         1        Ships
2820     100.00  5417.57       1         3        Ships
2821      62.24  2116.16       1         3        Ships
2822      65.52  3079.44       2         5        Ships

[2823 rows x 5 columns]

In [27]:
#df1[df1['STATE']=='NY']
df1.query("STATE == 'NY' and MONTH_ID==2")

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
54,10107,39,99.91,5,3896.49,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Medium
80,10107,27,100.00,4,6065.55,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Medium
240,10107,21,100.00,1,3036.60,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Medium
804,10107,29,70.87,6,2055.23,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1466,10107,25,100.00,3,2845.75,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1564,10107,38,83.03,7,3155.14,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Medium
2173,10107,20,92.90,8,1858.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small

In [28]:
df1.filter(like='ORDER')

      ORDERNUMBER  QUANTITYORDERED  ORDERLINENUMBER        ORDERDATE
0           10107               30                2   2/24/2003 0:00
1           10121               34                5    5/7/2003 0:00
2           10134               41                2    7/1/2003 0:00
3           10145               45                6   8/25/2003 0:00
4           10159               49               14  10/10/2003 0:00
...           ...              ...              ...              ...
2818        10350               20               15   12/2/2004 0:00
2819        10373               29                1   1/31/2005 0:00
2820        10386               43                4    3/1/2005 0:00
2821        10397               34                1   3/28/2005 0:00
2822        10414               47                9    5/6/2005 0:00

[2823 rows x 4 columns]

In [31]:
df1[(df1.STATE == 'NY') & (df1.QTR_ID==1)]

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
54,10107,39,99.91,5,3896.49,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Medium
80,10107,27,100.00,4,6065.55,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Medium
240,10107,21,100.00,1,3036.60,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Medium
475,10102,39,100.00,2,4808.31,1/10/2003 0:00,Shipped,1,1,2003,...,2678 Kingston Rd.,Suite 101,NYC,NY,10022,USA,NaN,Frick,Michael,Medium
501,10102,41,50.14,1,2055.74,1/10/2003 0:00,Shipped,1,1,2003,...,2678 Kingston Rd.,Suite 101,NYC,NY,10022,USA,NaN,Frick,Michael,Small
804,10107,29,70.87,6,2055.23,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1466,10107,25,100.00,3,2845.75,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1564,10107,38,83.03,7,3155.14,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Medium
2173,10107,20,92.90,8,1858.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small

In [34]:
df1.query("STATE == 'NY' and QTR_ID == 1")

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
54,10107,39,99.91,5,3896.49,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Medium
80,10107,27,100.00,4,6065.55,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Medium
240,10107,21,100.00,1,3036.60,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Medium
475,10102,39,100.00,2,4808.31,1/10/2003 0:00,Shipped,1,1,2003,...,2678 Kingston Rd.,Suite 101,NYC,NY,10022,USA,NaN,Frick,Michael,Medium
501,10102,41,50.14,1,2055.74,1/10/2003 0:00,Shipped,1,1,2003,...,2678 Kingston Rd.,Suite 101,NYC,NY,10022,USA,NaN,Frick,Michael,Small
804,10107,29,70.87,6,2055.23,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1466,10107,25,100.00,3,2845.75,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1564,10107,38,83.03,7,3155.14,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Medium
2173,10107,20,92.90,8,1858.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small

In [39]:
df1[['COUNTRY','CUSTOMERNAME']].groupby('COUNTRY').count()

             CUSTOMERNAME
COUNTRY
Australia             185
Austria                55
Belgium                33
Canada                 70
Denmark                63
Finland                92
France                314
Germany                62
Ireland                16
Italy                 113
Japan                  52
Norway                 85
Philippines            26
Singapore              79
Spain                 342
Sweden                 57
Switzerland            31
UK                    144
USA                  1004

In [41]:
df1[['STATE','PRICEEACH']].groupby('STATE').mean()

               PRICEEACH
STATE
BC             84.600000
CA             82.855769
CT             85.950328
Isle of Wight  81.991538
MA             84.198158
NH             83.362941
NJ             84.998095
NSW            83.194565
NV             80.441724
NY             84.633258
Osaka          82.121000
PA             85.789333
Quebec         86.193182
Queensland     84.736667
Tokyo          82.745000
Victoria       83.643462

In [46]:
#df1.sort_values(by = ['PRICEEACH'])
df1.sort_values(by = ['PRICEEACH'],ascending=True)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
1563,10420,45,26.88,1,1209.60,5/29/2005 0:00,In Process,2,5,2005,...,"Monitor Money Building, 815 Pacific Hwy",Level 6,Chatswood,NSW,2067,Australia,APAC,Huxley,Adrian,Small
1543,10162,37,27.22,5,1007.14,10/18/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Small
1724,10195,32,28.29,7,905.28,11/25/2003 0:00,Shipped,4,11,2003,...,3758 North Pendale Street,NaN,White Plains,NY,24067,USA,NaN,Frick,Steve,Small
1551,10280,20,28.88,12,577.60,8/17/2004 0:00,Shipped,3,8,2004,...,Via Monte Bianco 34,NaN,Torino,NaN,10100,Italy,EMEA,Accorti,Paolo,Small
1549,10227,42,29.21,6,1226.82,3/2/2004 0:00,Shipped,1,3,2004,...,"2, rue du Commerce",NaN,Lyon,NaN,69004,France,EMEA,Saveley,Mary,Small
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
702,10104,29,100.00,12,3772.61,1/31/2003 0:00,Shipped,1,1,2003,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
703,10114,39,100.00,3,4164.42,4/1/2003 0:00,Shipped,2,4,2003,...,"265, boulevard Charonne",NaN,Paris,NaN,75012,France,EMEA,Bertrand,Marie,Medium
704,10127,45,100.00,14,6295.95,6/3/2003 0:00,Shipped,2,6,2003,...,4092 Furth Circle,Suite 400,NYC,NY,10022,USA,NaN,Young,Jeff,Medium
673,10336,49,100.00,6,7460.74,11/20/2004 0:00,Shipped,4,11,2004,...,"265, boulevard Charonne",NaN,Paris,NaN,75012,France,EMEA,Bertrand,Marie,Large
1980,10225,40,100.00,4,4550.00,2/22/2004 0:00,Shipped,1,2,2004,...,Grenzacherweg 237,NaN,Gensve,NaN,1203,Switzerland,EMEA,Holz,Michael,Medium